### PR TITLE
Initial pass at integrating SWEET 'alignments' into Watchdog

### PR DESCRIPTION
**Pull request by lewismc**
Hi @carueda 
This is a first pass at bringing the SWEET alignment graphs into our growing linked data world served through COR. 
Although I live mostly on the JVM I don't write too much Scala so I am not sure if the code compiles and is accurate. This is to say, I don't quite know the return values for various statements so I don't really know whether the `alignments` data is being correctly interpreted alongside the existing `src` data.
It would be appreciated if you could take a look and let me know what you think. Hopefully the logic is clear.
Thanks

### CODE REVIEW

**Comment by lewismc** [comment]
Test ping

**Comment by lewismc** [comment]
test ping 2

**Review by carueda — COMMENTED** [review]
@lewismc Yeah, not sure what IDE you use, but I have trouble myself with IntelliJ not understanding these Ammonite scripts even though that it's supposed to provide [support for them](https://blog.jetbrains.com/scala/2018/05/07/ammonite-support/), which really makes me think about putting this code in a proper sbt (or mill) project for a more standard and complete support.

In the mean time, I'll look at your changes and report back.

**Comment by carueda** [comment]
@lewismc I've committed some changes .. and I've done some initial testing on COR toward any further adjustments..

**Comment by carueda** [comment]
Seems like this is now working (but more testing is needed). 

watchdog just registered a new version of `http://sweetontology.net/alignment/ssn`

It failed to register `http://sweetontology.net/alignment/dcat` because of permission: watchdog runs under the `sweetbot` username, but this ont is registered by `lmcgibbn`.

Anyway, so far good progress, please take a look at the commits.

**Comment by lewismc** [comment]
@carueda thanks for looking and adding to this.

> It failed to register http://sweetontology.net/alignment/dcat because of permission: watchdog runs under the sweetbot username, but this ont is registered by lmcgibbn.

I just deleted the existing `dcat` mapping so it should have no problems now.

**Comment by carueda** [comment]
@lewismc Ok, I just did the following
-  removed the `http://sweetontology.net/alignment/dcat` entry from `cor.csv`
- ran `./watchdog.sc update >> watchdog.cronjob.out`

The ontology has been registered.

I will now approve this PR and squash merge it.

**Comment by lewismc** [comment]
Thanks @carueda 
I saw your comments on the code... we can improve logic later once we onboard more hard alignments represented in individual graphs. For the time being this is good. Thanks for reviewing... I appreciate it.

**Pull request merged**
